[tool.poetry]
name = "ciphey"
version = "3.5.9"
description = "Automated Decryption Tool"
authors = ["Brandon <brandon@skerritt.blog>"]
license = "MIT"
documentation = "https://ciphey.readthedocs.io"
exclude = ["tests/hansard.txt"]

[tool.poetry.dependencies]
python = "^3.6"
tensorflow = "^2.1.0"
rich = "^1.2.3"
loguru = "^0.5.0"
pylint = "^2.5.2"
flake8 = "^3.8.2"
cipheydists = "^0.2.2"
cipheycore = "^0.1.5"
tflite-runtime = [
    {url = "https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp36-cp36m-linux_x86_64.whl", python="~3.6", markers="os_name == 'Linux'"},
    {url = "https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-linux_x86_64.whl", python="~3.7", markers="os_name == 'Linux'"},
    {url = "https://github.com/Ciphey/CipheyNeuralNetwork/raw/master/tflite/tflite_runtime-2.2.0-cp38-cp38-linux_x86_64.whl", python="~3.8", markers="os_name == 'Linux'"},
    {url = "https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp36-cp36m-macosx_10_14_x86_64.whl", python="~3.6", markers="os_name == 'Darwin'"},
    {url = "https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-macosx_10_14_x86_64.whl", python="~3.7", markers="os_name == 'Darwin'"},
    {url = "https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp36-cp36m-win_amd64.whl", python="~3.6", markers="os_name == 'Windows'"},
    {url = "https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-win_amd64.whl", python="~3.7", markers="os_name == 'Windows'"},
]
appdirs = "^1.4.4"
typing_inspect = { version = "^0.6.0", python = "~3.6 || ~3.7" }

[tool.poetry.dev-dependencies]
pytest-cov = "^2.9.0"
pytest = "^5.4.3"
black = "^19.10b0"
neovim = "^0.3.1"
codecov = "^2.1.4"
safety = "^1.9.0"
sphinx = "^3.0.4"
sphinx-autodoc-typehints = "^1.10.3"
nltk = "^3.5"

[tool.poetry.scripts]
ciphey = 'ciphey.__main__:main'
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


